// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdmcnnyuiyzmazdakglz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkbWNubnl1aXl6bWF6ZGFrZ2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDE4NDEsImV4cCI6MjA2Mjg3Nzg0MX0.LuYTSeq3saeIkH6KJUBUagJhTHvSKJN837HB8A1K4jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);